CREATE SCHEMA IF NOT EXISTS DATA;

USE DATA

CREATE TABLE IF NOT EXISTS USERS
(
  USER_ID     INT  AUTO_INCREMENT PRIMARY KEY,
  LOGIN       VARCHAR(255),
  ENC_PASS    VARCHAR(255),
  DESCRIPTION VARCHAR(500),
  ALLOWED_IPS VARCHAR(10000),

  UNIQUE KEY (LOGIN)
);

CREATE TABLE IF NOT EXISTS BROKER_TYPES(

  BROKER_TYPE VARCHAR(20) PRIMARY KEY

);

CREATE TABLE IF NOT EXISTS RESOURCE_TYPES (

  RESOURCE_TYPE  VARCHAR(50),
  BROKER_TYPE VARCHAR(20),

  PRIMARY KEY (RESOURCE_TYPE, BROKER_TYPE),
  FOREIGN KEY (BROKER_TYPE) REFERENCES BROKER_TYPES(BROKER_TYPE)
);

CREATE TABLE IF NOT EXISTS EVENTS
(
  EVENT_ID    INT PRIMARY KEY,
  DESCRIPTION VARCHAR(500)
);


CREATE TABLE IF NOT EXISTS RESOURCES
(
  RESOURCE_ID INT AUTO_INCREMENT PRIMARY KEY,
  BROKER_TYPE VARCHAR(20),
  RESOURCE_TYPE  VARCHAR(50),
  RESOURCE_NAME VARCHAR(100),
  DESCRIPTION VARCHAR(500),

  UNIQUE KEY (BROKER_TYPE, RESOURCE_TYPE, RESOURCE_NAME),
  FOREIGN KEY (RESOURCE_TYPE, BROKER_TYPE) REFERENCES RESOURCE_TYPES(RESOURCE_TYPE,BROKER_TYPE)

);


CREATE TABLE IF NOT EXISTS PERMISSION_MODES
(
  PERMISSION_MODE VARCHAR(20) PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS ROLES
(
  ROLE_ID INT AUTO_INCREMENT PRIMARY KEY,
  PERMISSION_MODE VARCHAR(20),
  RESOURCE_ID INT,

  UNIQUE KEY (RESOURCE_ID, PERMISSION_MODE),

  FOREIGN KEY (RESOURCE_ID) REFERENCES RESOURCES(RESOURCE_ID),

  FOREIGN KEY (PERMISSION_MODE) REFERENCES PERMISSION_MODES(PERMISSION_MODE)

);

CREATE TABLE IF NOT EXISTS USER_ROLES
(
  ID INT AUTO_INCREMENT PRIMARY KEY,
  USER_ID INT,
  ROLE_ID INT,

  UNIQUE KEY (USER_ID, ROLE_ID),

  FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),

  FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ROLE_ID)

);

CREATE TABLE IF NOT EXISTS EVENT_RESOURCES
(
  ID INT AUTO_INCREMENT PRIMARY KEY,
  EVENT_ID INT,
  RESOURCE_ID INT,

  UNIQUE KEY (EVENT_ID, RESOURCE_ID),

  FOREIGN KEY (EVENT_ID) REFERENCES EVENTS(EVENT_ID),

  FOREIGN KEY (RESOURCE_ID) REFERENCES RESOURCES(RESOURCE_ID)
);




