USE DATA

INSERT INTO users(LOGIN, ENC_PASS, DESCRIPTION, ALLOWED_IPS)
VALUES ('test_user1', 'qwerty', 'description user1', '127.0.0.1, 127.0.0.2');

INSERT INTO users(LOGIN, ENC_PASS, DESCRIPTION, ALLOWED_IPS)
VALUES ('test_user2', 'qwerty2', 'description user2', '127.0.0.1, 127.0.0.2');



INSERT INTO EVENTS(EVENT_ID, DESCRIPTION) values (101, 'shape process 1');

INSERT INTO BROKER_TYPES(BROKER_TYPE) VALUES ('kafka');
INSERT INTO BROKER_TYPES(BROKER_TYPE) VALUES ('artemis');

INSERT INTO RESOURCE_TYPES(BROKER_TYPE, RESOURCE_TYPE) VALUES ('kafka', 'topic');
INSERT INTO RESOURCE_TYPES(BROKER_TYPE, RESOURCE_TYPE) VALUES ('artemis', 'queue');

INSERT INTO RESOURCES(BROKER_TYPE, RESOURCE_TYPE, RESOURCE_NAME, DESCRIPTION)
VALUES('kafka', 'topic', 'shapeKafkaTopic', 'topic for shaping events');

INSERT INTO RESOURCES(BROKER_TYPE, RESOURCE_TYPE, RESOURCE_NAME, DESCRIPTION)
VALUES('kafka', 'topic', 'topicAnalyst', 'topic for analytics');


INSERT INTO PERMISSION_MODES(PERMISSION_MODE) VALUES('all');
INSERT INTO PERMISSION_MODES(PERMISSION_MODE) VALUES('write');
INSERT INTO PERMISSION_MODES(PERMISSION_MODE) VALUES('read');

INSERT INTO ROLES(PERMISSION_MODE, RESOURCE_ID) VALUES ('read', '1');
INSERT INTO ROLES(PERMISSION_MODE, RESOURCE_ID) VALUES ('write', '1');

INSERT INTO ROLES(PERMISSION_MODE, RESOURCE_ID) VALUES ('read', '2');
INSERT INTO ROLES(PERMISSION_MODE, RESOURCE_ID) VALUES ('write', '2');

INSERT INTO USER_ROLES(USER_ID, ROLE_ID) VALUES(1,1);
INSERT INTO USER_ROLES(USER_ID, ROLE_ID) VALUES(1,2);
INSERT INTO USER_ROLES(USER_ID, ROLE_ID) VALUES(1,3);
INSERT INTO USER_ROLES(USER_ID, ROLE_ID) VALUES(1,4);
INSERT INTO USER_ROLES(USER_ID, ROLE_ID) VALUES(2,1);
INSERT INTO USER_ROLES(USER_ID, ROLE_ID) VALUES(2,2);


INSERT INTO EVENT_RESOURCES(EVENT_ID, RESOURCE_ID) VALUES (101, 1);
INSERT INTO EVENT_RESOURCES(EVENT_ID, RESOURCE_ID) VALUES (101, 2);

COMMIT;